UPDATE tb_order ORD
INNER JOIN 
(
SELECT A.ORD_NO, A.ID, SUMQTY, B.UNIT_PRICE, C.DISCOUNT, SUM(SUMQTY*B.UNIT_PRICE*(100-C.DISCOUNT)/100) TOTAL
FROM (
SELECT ORD_NO, ID, SUM(QTY) SUMQTY
FROM tb_order_detail 
GROUP BY ID,ORD_NO
HAVING ORD_NO = 'HD1'
) as A
LEFT JOIN tb_item B
ON A.ID = B.ID
LEFT JOIN tb_order C
ON A.ORD_NO = C.ORD_NO
GROUP BY A.ORD_NO
) D
ON ORD.ORD_NO = D.ORD_NO
SET 
	ORD.TOTAL = D.TOTAL
;