UPDATE tb_item ITEM
INNER JOIN 
(
SELECT A.ID, B.QTY, A.SUMSELL, SUM(B.QTY-A.SUMSELL) SUMQTY
FROM (
SELECT ID, SUM(QTY) SUMSELL
FROM tb_order_detail 
GROUP BY ID
) as A
LEFT JOIN tb_item B
ON A.ID = B.ID
GROUP BY A.ID
) D
ON ITEM.ID = D.ID
SET 
	ITEM.QTY = D.SUMQTY
;